version: "3.1"
services:
  master:
    image: "mariadb:latest"
    restart: always
    volumes:
      - ./db_config/master_conf:/etc/mysql/conf.d:z
      - ./db_init/master_init:/docker-entrypoint-initdb.d:z
      - ./logs/master_logs:/var/lib/mysql
    environment:
      MARIADB_ROOT_PASSWORD: $MARIADB_ROOT_PASSWORD
      MYSQL_INITDB_SKIP_TZINFO: "Y"
      REPLICA_USER: $REPLICA_USER
      REPLICA_PASSWORD: $REPLICA_PASSWORD
    working_dir: /var/lib/mysql
    ports:
      - 3306:3306
  replica:
    depends_on:
      - master
    image: "mariadb:latest"
    restart: always
    volumes:
      - ./db_config/replica_config:/etc/mysql/conf.d:z
      - ./db_init/replica_init:/docker-entrypoint-initdb.d:z
      - ./logs/replica_logs:/var/lib/mysql
    environment:
      MARIADB_ROOT_PASSWORD: $MARIADB_ROOT_PASSWORD
      MYSQL_INITDB_SKIP_TZINFO: "Y"
      REPLICA_USER: $REPLICA_USER
      REPLICA_PASSWORD: $REPLICA_PASSWORD
    working_dir: /var/lib/mysql
    links:
      - master:master
    ports:
      - 3307:3306
